package com.adp.appsilvant.data

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
data class MediaVisto(
    val id: Long = 0, // Generated by the database
    @SerialName("media_id")
    val mediaId: Int,
    val titulo: String,
    val tipo: String, // 'movie' or 'tv'
    val estado: String = "viendo",
    val valoracion: Int? = null,
    @SerialName("poster_path")
    val posterPath: String? = null,
    @SerialName("creado_en")
    val creadoEn: String? = null // Generated by the database
)
