package com.adp.appsilvant.data

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

// NOTE: This class now perfectly matches the 'viajes' table schema.
@Serializable
data class Viaje(
    // Default values are used when creating a new 'Viaje' to send to the database,
    // as 'id' and 'creadoEn' are generated by the database itself.
    val id: Long = 0,
    val lugar: String, // Matches 'lugar TEXT NOT NULL'
    val fecha: String? = null,
    val descripcion: String? = null,
    @SerialName("creado_en") // Maps the database column 'creado_en' to this field
    val creadoEn: String? = null,
    @SerialName("fotos_viajes")
    val fotos: List<FotoViaje> = emptyList()
)
